# coding=utf8

d['NAME'] = u'WWWWWWWWWWWWWWWWWWWWW'
d['AVATAR'] = 3

d['ARTIST'] = u'WWWWWWWW'
d['ALBUM'] = u'WWWWWWWWW'
d['COUNTRY'] = u'WWWWWWWWWWWWW'
d['YEAR'] = u'WWWWWWWWWWWWWWWWW'
d['STYLE'] = u'WWWWWWWWWWWWWWWWW'
d['DURATION'] = u'WWWWWWWWWWWWWWWWW'
d['CODEC'] = u'WWWWWWWWWWWWWWWW'

d['TRACKLIST'] = u'''
WWWWWWWWWWWWWWWWW
'''

d['OTHER'] = u'''
WWWWWWWWWWWWWWWWWWWWWWWWWW
'''
